### ISSUE TITLE
Documentation formatting issue

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1229]
### Short description of the issue

The indentation of bulleted lists isn't correct on some pages in the PW documentation, so there might need to be an adjustment to the script that parses the documentation from the PhpDoc comments.

Examples...

https://processwire.com/api/ref/sanitizer/camel-case/
![2020-08-12_103331](https://user-images.githubusercontent.com/1538852/89955537-5c922a00-dc87-11ea-88ad-d81ff9d94875.png)

https://processwire.com/api/ref/sanitizer/hyphen-case/
![2020-08-12_103354](https://user-images.githubusercontent.com/1538852/89955547-61ef7480-dc87-11ea-8317-7d8120c4fefd.png)

This could cause confusion - taking the first example above, it looks like "allow" expects an array value with "allowUnderscore", "startLowercase" and "startNumber" being keys of the nested array. But actually `$options` is just a single-level array.

**Comment by ryancramerdesign** [comment]
@Toutouwai I'm not seeing this in the documentation currently at the links you indicated, so am thinking that whatever was causing it was likely fixed at some point. I'll close this, though let me know if you observe the issue anywhere else. Thanks.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign I see it, just like in the screenshot from Robin.

**Comment by Toutouwai** [comment]
I'm still seeing it here - I tested in several different browsers, and I can see the incorrect extra `<ul>` markup in the source code:

![2021-08-05_103159](https://user-images.githubusercontent.com/1538852/128263987-b0416927-66c0-4134-9f7f-b165d8526e26.png)

**Comment by ryancramerdesign** [comment]
@Toutouwai @matjazpotocnik Just tried with an incognito window and now I see it. Looks like there must be some really old cache files stuck because if you append a query string to the URL then everything appears correct, i.e. <https://processwire.com/api/ref/sanitizer/camel-case/?a=b>

**Comment by teppokoivula** [comment]
> Looks like there must be some really old cache files stuck because [...]

Not sure if this is directly related, but I've noticed that certain other parts of the site, such as the sites directory, also take a while (sometimes a few weeks, if not more) to update. Appending a GET param helps (for that query, but it doesn't seem to flush anything behind the scenes).

**Comment by ryancramerdesign** [comment]
@teppokoivula It could be related. It's strange because the document cache is completely empty, so I don't know where that output is coming from. So far my best guess is that one of the load balancer nodes is off track and must have some old cache files in it.

**Comment by Toutouwai** [comment]
Looks like the cached files have been cleared - the bulleted lists on those two documentation pages are displaying correctly for me now. Thanks.
