### ISSUE TITLE
Users lister forgets pagination on page reload

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1780]
### Short description of the issue

When using the core Find lister, if I am on page 2 of the results and I reload the admin page in my browser then I am still on page 2 - the lister remembers the pagination.

This doesn't happen in the Users lister. If I am on page 2 of the results in the Users lister and I reload the page I am back on page 1.

### Expected behavior

Standard Lister features are available on all instances of Lister.

### Setup/Environment

* ProcessWire version: 3.0.222

**Comment by Toutouwai** [comment]
It actually seems to relate to if the user has changed the filters from their defaults (pagination is forgotten if filters are at their defaults), but I don't understand why the pagination memory ought to depend on that.

**Comment by ryancramerdesign** [comment]
@Toutouwai I think this isn't an issue with the users lister but rather just the way that ProcessPageLister decides when it should reset. I have pushed a change that I think will fix it, but have tested it with other listers rather than the Users one (I don't have enough users to paginate, though can add them if need be). Do you find the committed adjustment fixes the issue? Thanks.

**Comment by Toutouwai** [comment]
@ryancramerdesign, the issue is still occurring with the latest commits.

Reloading the Users lister with the filters at their default - the pagination is forgotten:

![users1](https://github.com/processwire/processwire-issues/assets/1538852/cc6e9101-5696-45f8-b45d-dc1e5305b53e)

Reloading the Users lister with any of the filter settings changed (in this case the limit). In this scenario the pagination is remembered:

![users2](https://github.com/processwire/processwire-issues/assets/1538852/bea44104-adc9-4476-9ea3-c90968a844d1)

**Comment by ryancramerdesign** [comment]
@Toutouwai It looks like my previous fix only worked for ListerPro. I just pushed another update that should make it also work with regular Lister. Can you confirm? Thanks.

**Comment by Toutouwai** [comment]
Yes, it's working with the Users lister now. Thanks.
