### ISSUE TITLE
In a repeater item, Pagefile/image’s custom fields are not saved on first save after upload

### ISSUE THREAD

**Issue by romaincazier** [processwire/processwire-issues#2060]
### Description of the issue

In a setup where you have a Repeater containing an InputfieldFile/Image with custom fields: if you upload an image, edit its custom fields and then hit “Save”, nothing is actually saved and the values are blank. If you try again, the values are then correctly saved.

This bug doesn’t occur if the InputfieldFile/Image is not within a Repeater.

### Setup

ProcessWire 3.0.247

**Comment by ryancramerdesign** [comment]
Thanks @romaincazier I've pushed a fix for this issue.

**Comment by brodiefarrell** [comment]
This issue is still occuring for us on 3.0.246, reverting back to 3.0.244 has fixed the issue for us.

**Comment by matjazpotocnik** [comment]
@brodiefarrell, I think this is fixed. Closing. Please open a new issue if not fixed.
