### ISSUE TITLE
PW > 3.0.74: User can't upload files to Repeater Matrix

### ISSUE THREAD

**Issue by processwired** [processwire/processwire-issues#403]
### Short description of the issue

If ProcessWire is version 3.0.75 or higher, a user (without admin permissions) can't upload files to a Repeater Matrix type, if this type has a file or image field assigned. Please see attached gif; Chrome Dev Console shows no errors.

![upload](https://user-images.githubusercontent.com/8448399/31491553-0818f41e-af48-11e7-99bd-1256b5b561a6.gif)

### Expected behavior

Files should successfully be uploaded, like it was in 3.0.74 and before.

### Actual behavior

The files get deleted without any error. They just vanish.

* ProcessWire version: 3.0.75 and higher

**Comment by processwired** [comment]
To be more precise, I tested through all the commits: the commit [6fef531b1aaa4e9c3592c7f2a02f6a30e93cb89b](https://github.com/processwire/processwire/commit/6fef531b1aaa4e9c3592c7f2a02f6a30e93cb89b) introduced the problem.

**Comment by cb2004** [comment]
I am also having problems with this.

**Comment by cb2004** [comment]
@processwired do you have ProDrafts as well as I thought it was possibly related to that?

**Comment by processwired** [comment]
Nope, no ProDrafts installed. I think it really depends on the code change "Some optimizations to FieldtypeRepeater" done [here](https://github.com/processwire/processwire/commit/6fef531b1aaa4e9c3592c7f2a02f6a30e93cb89b) as mentioned before.

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue.

**Comment by processwired** [comment]
Thanks a lot for quick response, Ryan. Maybe it's just me and my setup, but I still can't upload an image with latest 3.0.79. The AJAX request in console returns: {"error":false,"message":"The requested process does not exist"}

**Comment by processwired** [comment]
Tried again with another clean install setup - just ProcessWire 3.0.79 and Repeater Matrix 0.0.4 are installed. I can confirm that the mentioned problem does exist here too, so I'm quite sure that it hasn't to do with my setup. Heads up: one has to use normal editor permissions to notice the problem - with super user rights all is well.

**Comment by processwired** [comment]
(I hope I'm not too pesky) - @cb2004 is right: I did another test with ProDrafts 0.0.6a and this time commit cc34ec8752bbeef897cd86fb55204a3597c40bed shows the same problem, which was the most current commit working (without ProDrafts). To summarize: without ProDrafts installed, the problem is introduced by commit [6fef531b1aaa4e9c3592c7f2a02f6a30e93cb89b](https://github.com/processwire/processwire/commit/6fef531b1aaa4e9c3592c7f2a02f6a30e93cb89b). With ProDrafts installed, the problem occurs even with versions older than that.

**Comment by ryancramerdesign** [comment]
Try pulling from today's commits, as I think one in there fixes it. Also an updated version of ProDrafts is posted in the boards (version 6b), so you'd want to grab that too, even though the actual fix is in the core.

**Comment by processwired** [comment]
Without ProDrafts installed, the upload of images/files within Repeater Matrix seems to work again - thanks a lot, Ryan :-) With ProDrafts, something weird happens: the image gets uploaded fine, but when clicking "Save Draft", it takes some seconds and redirects to the frontend. "Publish" works, though.

**Comment by ryancramerdesign** [comment]
So far I can't duplicate that. File/image field in a Repeater Matrix seems to be working fine here when uploading a file and saving a draft. Can you think of anything else that might be affecting it?

**Comment by cb2004** [comment]
@netcarver Hi Steve. This was down to ProDrafts and was fixed at some point. Closed is fine.
