### ISSUE TITLE
Relative path issue in wireIncludeFile

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#511]
### Short description of the issue

Methods in the WireFileTools class, like `include` use relative paths so if you use `wireIncludeFile()` or `$files->include()` from a module the file is not included because the path is something like: `./templates/fileToInclude.php`

### Expected behavior

It should work no matter where it's called from.

### Actual behavior

You get an error triggered by https://github.com/processwire/processwire/blob/a9ec5a640ac0442d3980d2cd33770626aafc91a2/wire/core/WireFileTools.php#L730

### Optional: Suggestion for a possible fix

Convert path to filename to be absolute.

### Setup/Environment

* ProcessWire version: 3.0.94

**Comment by Toutouwai** [comment]
I use `$files->render()` via the wireRenderFile() function in a module and it works okay. There is the `defaultPath` option available.

I don't see a `defaultPath` option for `$files->include()` - maybe this option should be added, or perhaps you are able to include files from any of the `allowedPaths` (which includes the /site/modules directory by default) already?

**Comment by adrianbj** [comment]
Thanks for chiming in @Toutouwai 

Maybe I should have been a little more explicit - I am actually hoping that Zeka from the PW forums will chime in (not sure his Github handle) because he found this with the Tracy console panel.

If you put something like this: `wireIncludeFile('templates/fileToInclude');` in ready.php, the Console panel gets the file doesn't exist error because it renders a template, but obviously from the Tracy module's path, rather than from site/templates. I think he also had issues when using that from a module. In reality I think there might be several scenarios where this could show up, but I think adding `$config->paths->root` to the front of all rendered files would fix it. Maybe I am missing something though as I haven't investigated thoroughly.

**Comment by Lazerproof** [comment]
@adrianbj Thank you for opening this issue.
Actually, I'm not sure that initial post of the issue correctly describes it. 

When I put this line in ready.php `wireIncludeFile('templates/helpers/translations');` file is successfully included, but it somehow influence how Console panel from TracyDeggur works. It begins to output whole render of the page instead of the result of code execution.

In my case, I didn't get the exception from this line https://github.com/processwire/processwire/blob/a9ec5a640ac0442d3980d2cd33770626aafc91a2/wire/core/WireFileTools.php#L730 , but commenting this line fixes described behavior of the Console panel. Also using include_once or require_once fixes it. 

How to reproduce it:
1. Install Tracy Debugger
2. Use wireIncludeFile to include some file from ready.php
3. Try to use Tracy`s Console panel. 

I've tested this behavior on two different installations of the latest PW. 
So, I don't know where is a bug and would ask to help to investigate it.

**Comment by adrianbj** [comment]
Thanks for contributing @Lazerproof - I also don't see any error when viewing the site, but I also don't think this is specific to Tracy. In that example where a wireIncludeFile is added to ready.php, from what I can tell any module that results in ready.php being loaded will trigger that "file does not exist" error because the path to the included file will be relative to the root of the module, rathe than /site/

Hopefully between us we've now managed to explain this a little better :)

**Comment by ryancramerdesign** [comment]
I'm not sure I understand the issue report. File functions (whether PHP's or PW's) operate from the [current working directory](http://php.net/manual/en/function.getcwd.php), not from the directory that the caller's file lives in (which it would have no way of knowing). During execution, ProcessWire sets the current working directory to the dir of whatever file is being rendered, i.e. /site/templates/. So any file function that you call (whether one from PHP or PW or anything else), a relative path is going to be relative to that directory. Unless you have set the current working directory [chdir()](http://php.net/manual/en/function.chdir.php) on your own, don't call file functions with relative paths. If you want something relative to the file of where you make the call, then use `__DIR__ . '/myfile.php'` so that it translates to the intended full path. Also, `$files->render()`is a little different in that it lets you specify the starting point for relative paths (defaultPath), with the default being /site/templates/. But if you are using these functions (or any PHP file functions) somewhere other than template files, prepend a `__DIR__` to your relative path so that you are not passing a relative path to a function without knowing the current working directory. PW can't do this for you because `__DIR__` and `__FILE__` always reflect the dir/file of the file they are placed in.

**Comment by adrianbj** [comment]
@ryancramerdesign - maybe this is an unusual situation, but Tracy's Console panel uses:
 `new TemplateFile()` to render the output of whatever code is run. Because this starts PW it also calls any `wireIncludeFile()` calls in ready.php. While the relative path works normally, it doesn't work when triggered by `new TemplateFile()`.

Probably the easiest way for you to see what is going on is to follow @Lazerproof 's instructions above. I didn't mention Tracy in my OP because I think it's very possible this could occur in other future modules as well. The dev adding a wireIncludeFile shouldn't have to consider the path to the root when using `wireIncludeFile()`. Is there any logical way you can simply prepend `$config->paths->site` so that it works as expected everywhere, or will that break the logic that others might currently be relying on? Or do you have any other suggestions for a way that modules (like Tracy) can make a call to `new TemplateFile()` without breaking their functionality?

Thanks.

**Comment by netcarver** [comment]
@ryancramerdesign Do you have enough information to proceed?

**Comment by adrianbj** [comment]
@ryancramerdesign - you state that this is not a bug, but could you please confirm that you tested as per @Lazerproof 's instructions above? I still think this could easily be solved by prepending `$config->paths->site` to the path. What do you think?

**Comment by adrianbj** [comment]
**Root cause**

`$files->include()` / `wireIncludeFile()` resolve a relative filename against PHP's **current working directory** — `___include()` forces `./` onto any non-absolute path, so the include depends entirely on whatever `getcwd()` happens to be.

That cwd is set in `ProcessWire::includeFile()`:

```php
$this->pathSave = getcwd();
chdir(dirname($this->fileSave));
```

For `ready.php` it normally chdirs to `/site/`, so `wireIncludeFile('templates/foo')` resolves to `/site/templates/foo.php`. **But** a few lines earlier, when `$config->templateCompile` is on and status is past boot (ready = 4 > boot = 1), `$this->fileSave` is swapped for the *compiled* copy of the file:

```php
if($this->status > self::statusBoot && $config->templateCompile) {
    if($files) $this->fileSave = $files->compile($file, array('skipIfNamespace' => true));
}
```

So the chdir target becomes `/site/assets/cache/FileCompiler/site/` instead of `/site/`, and the relative include silently breaks. That's why it surfaces under Tracy's Console panel (which boots/renders through compiled paths) but not in a plain front-end request — it's purely a matter of which cwd is active when the relative path is evaluated. It isn't Tracy-specific; any context that compiles `ready.php` hits it.

This is also exactly the inconsistency @Toutouwai flagged: `$files->render()` already sidesteps cwd entirely via its `defaultPath` option (default `/site/templates/`), but `$files->include()` has no equivalent.

**Proposed fix**

Give `___include()` the same `defaultPath` option as `___render()`, so relative includes can resolve against a stable base instead of the cwd. Keeping the default empty makes it fully backwards-compatible (current cwd behaviour unchanged); callers like Tracy can pass `defaultPath`, and `wireIncludeFile()` relative paths become robust regardless of compilation/cwd:

```diff
 		$defaults = array(
 			'func' => 'include',
 			'autoExtension' => 'php',
+			'defaultPath' => '', // base for relative filenames; blank = use current working dir (legacy behavior)
 			'allowedPaths' => array(
 				$paths->templates,
 				$paths->adminTemplates,
 				$paths->modules,
 				$paths->siteModules,
 				$paths->cache
 			)
 		);

 		// need to use different name than $options
 		$options = array_merge($defaults, $options);
 		$filename = trim($filename);

 		// add .php extension if filename doesn't already have an extension
 		if($options['autoExtension'] && !strrpos(basename($filename), '.')) {
 			$filename .= '.' . $options['autoExtension'];
 		}

+		// resolve a relative filename against defaultPath (rather than the current working dir)
+		if($options['defaultPath'] && strpos($filename, '/') !== 0 && strpos($filename, ':') !== 1) {
+			if(strpos($filename, './') === 0) $filename = substr($filename, 2);
+			$filename = rtrim($options['defaultPath'], '/') . '/' . $filename;
+		}
+
 		if(strpos($filename, '..') !== false) {
```

Because a set `defaultPath` produces an absolute path, the existing allowed-paths check still applies, so it can't be used to reach outside the permitted directories.

If you'd prefer it to "just work" without callers opting in, defaulting `defaultPath` to `$paths->templates` (matching `render()`) would do it — but that changes the base for existing relative includes from cwd to `/site/templates/`, so the opt-in default above is the safer choice.

**Comment by ryancramerdesign** [comment]
Thanks Adrian. This is now fixed on the dev branch in processwire/processwire@189304e8. The underlying issue was that ProcessWire::includeFile() changed the working directory to the FileCompiler cache location when executing a compiled status file such as ready.php. It now includes the compiled copy while retaining the original source file's directory as cwd, matching the method's documented behavior and the approach already used by PageRender. This addresses relative wireIncludeFile()/file operations generally without adding a new opt-in defaultPath behavior. Regression coverage forces a source file through FileCompiler and verifies the original cwd during execution and restoration afterward.

**Comment by adrianbj** [comment]
Sorry @ryancramerdesign - this doesn't seem to fix the issue for me. 

<img width="692" height="150" alt="Image" src="https://github.com/user-attachments/assets/f6c5fd9d-3919-4f62-8e70-a5a8177ff04c" />
