### ISSUE TITLE
Inputfield::render full HTML support of Inputfields description, notes

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#569]
### Short description of the issue

I need full html support for descriptions and notes of some Inputfields, because I need to include a link which opens a pw-modal. With a hook in **Inputfield::render** I applied _textformatters (markdown) + allow html_ but got unexpected results. Mistakenly the provided html is wrapped twice in `<p>` tags:
```
<p class='description'><p>Description goes here</p></p>
```

The hook:
```
$this->addHookBefore('Inputfield::render', function ($e) {
	if (!in_array($e->object->name, array('field1','field2'))) return;
	$e->object->set('textFormat', 8); // 2 none , 4 default, 8 extra including full html support
});

```
### Expected behavior
No `<p>` wrapper in case of full html support

### Actual behavior

As a work-around I used this hook to remove `<p>` wrapper for descriptions and notes. 
```
$this->addHookAfter('Inputfield::render', function ($e) {
	// if ($e->object->has())
	$e->return = str_replace(array("<p class='description'><p>",'</p></p>'), array('<p class="description">','</p>'), $e->return);
	$e->return = str_replace(array("<p class='notes'><p>",'</p></p>'), array('<p class="notes">','</p>'), $e->return);
});

```
In case of errors the error notice is wrapped in `<p>` tags as well:
`<span><p>Missing required value</p></span>` corrected by the browser to `<span></span><p>Missing required value</p>`

![bildschirmfoto 2018-04-20 um 17 45 55](https://user-images.githubusercontent.com/4683120/39061233-ed595af8-44c3-11e8-8497-c655393a8f44.jpg)

* ProcessWire version: latest dev

**Comment by Toutouwai** [comment]
I think the expectation is that description and notes is only ever a single paragraph. I guess you are saying here that it would be good if you could use multiple paragraphs, divs, etc in the description/notes when using the full markdown/html textformat.

If you in fact only want a single paragraph then you can apply the Paragraph Stripper textformatter after the markdown textformatter. The Paragraph Stripper textformatter is designed for just this sort of case when you want markdown applied to contents only without adding a wrapping element.

**Comment by adrianbj** [comment]
I think this will achieve what you want: http://modules.processwire.com/modules/dynamic-description-notes/

There is an Allow HTML option.

**Comment by kixe** [comment]
@Toutouwai 
@adrianbj 
Thanks for your input. But this is not a help forum. I want to report a bug and this is a bug.
I didn't put any block elements in the description field, just inline tags. The system wraps it in double `<p>` tags.

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue.

**Comment by kixe** [comment]
Thanks, but your fix does not work properly. Now the wrapper is replaced by a simple `<p>` tag.
CSS classes: 'description' and 'notes' are removed. In case of errors the complete error wrapper `<p>` with classes, the `<i>` tag with icon and the inner `<span>` is replaced by a simple `<p>`

**Comment by kixe** [comment]
No I got it. I just have to disable **entityEncodeText** to get what I need and which works properly without your fix.
```
	$this->addHookBefore('Inputfield::render', function ($e) {
		$e->object->set('entityEncodeText', false);
	});
```
 But I still don't understand why  I have to set **entityEncodeText** to **false** manually if I already have set
`$inputfield->textFormat = Inputfield::textFormatMarkdown`
which includes full html support.

The fix should remove the `<p>` wrapper apllied by 
**Sanitizer::entitiesMarkdown()** for descriptions, notes and errors.

**Comment by ryancramerdesign** [comment]
> Thanks, but your fix does not work properly. Now the wrapper is replaced by a simple <p> tag.
CSS classes: 'description' and 'notes' are removed.

That's because markdown wraps with `<p>` tags. You were getting double paragraph tags before because there was PW's one, followed by Markdown's. 

> In case of errors the complete error wrapper <p> with classes, the <i> tag with icon class and the inner <span> is replaced by a simple <p>

Full markdown defines block-level elements, rather than just inline ones, so we technically shouldn't take markdown output and wrap it with anything else. 

> No I got it. I just have to disable entityEncodeText to get what I need and which works properly without your fix.

If you opt for that, you don't have to use markdown at all. 

> The fix should remove the <p> wrapper apllied by Sanitizer::entitiesMarkdown() for descriptions, notes and errors.

This is what the `Inputfield::textFormatBasic` option is, which implies just inline-level element markdown. Full markdown can include block-level elements, so there just isn't any way to support full markdown while still using our wrappers. So full markdown support wasn't working quite right before, and your issue report is what pointed to the problem. Thanks.

**Comment by kixe** [comment]
Thanks.
