### ISSUE TITLE
Muted active tab in Modules, Edit Template, Edit Field, etc.

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#853]
### Short description of the issue

The first tab, or the "initial" one (the tab activated through a direct URL such as in the case of /processwire/module/?core), gets a "muted" style.

This is likely related to #847.

### Expected behavior

The first / initial tab shouldn't differ visually from other tabs, unless there's a good reason for this behaviour. Currently the style difference makes that tab seem "disabled".

### Optional: Screenshots/Links that demonstrate the issue

<img width="273" alt="Screen Shot 2019-04-13 at 17 56 34" src="https://user-images.githubusercontent.com/1252021/56081538-29335700-5e17-11e9-86e2-e9957fc8c168.png">
<img width="282" alt="Screen Shot 2019-04-13 at 17 51 47" src="https://user-images.githubusercontent.com/1252021/56081541-2d5f7480-5e17-11e9-91ab-15d82df4bc8a.png">

### Setup/Environment

* ProcessWire version: 3.0.130

**Comment by Toutouwai** [comment]
I think it's actually the same issue as #847 rather than related to it. The issue was fixed but the old JS is probably cached in the browser. @ryancramerdesign, it looks like the admin themes only change the cache-busting query string when the admin theme version number changes, so do the core admin themes need a version bump?

**Comment by teppokoivula** [comment]
@Toutouwai, I've been testing this with dev tools open and "disable cache" option enabled, and this problem still occurs in the latest dev branch version. Just did a quick test on another browser, and no change – it's not a browser cache issue.

**Comment by teppokoivula** [comment]
Actually it might indeed be the same issue – I'm seeing exactly the same issue here: if I open an URL such as /processwire/setup/field/edit?id=108#fieldtypeConfig, the active tab is muted there as well.

Doesn't seem like a browser cache problem, since I'm also experiencing this in another browser that I've never loaded the admin of this site with. I'm also running the latest dev branch version.

What am I missing here? :)

**Comment by teppokoivula** [comment]
Found the issue: it was indeed a caching problem, but not at browser level, but rather at Cloudflare. Had to manually purge the cache at their management panel to get the new version of the main.js file.

Sorry for the false alarm folks – closing this issue now :)

**Comment by teppokoivula** [comment]
For the record, what @Toutouwai suggested above (bumping admin theme version) would've likely solved this as well, so it might still be a good idea to do just that. Ping @ryancramerdesign 👍
